- name: run new fetcher container and mount local code
  command: "docker run -d -P --name {{ ident }}_econ_fetcher -v /econ/econ-fetcher:/src/ --link {{ ident }}_db_mongo:mongodb -p {{ port_db_ssh }}:22 econ/econ-fetcher-latest"
  sudo: yes