- name: run new database server container and mount local code
  command: "docker run -d -P --name {{ ident }}_econapp -v /econ/econ-server:/src/ -v /econ/mongodata:/data/db --link {{ ident }}_db_mongo:mongodb -p {{ port_db }}:5000 -p {{ port_db_ssh }}:22 econ/econapp-latest"
  sudo: yes