- name: stop econ client container
  command: "docker stop {{ ident }}_econ_client"
  sudo: yes
  ignore_errors: yes
- name: remove econ client container
  command: "docker rm {{ ident }}_econ_client"
  sudo: yes
  ignore_errors: yes