- name: run new database server container and mount local code
  command: "docker run -d -P --name {{ ident }}_econapp -v /econ/econ-db:/src/ --link {{ ident }}_db_mongo:db -p {{ port_dw }}:5000 -p {{ port_dw_ssh }}:22 econ/econ/econapp-latest"
  sudo: yes