-

  hosts: "{{ host }}"
  tasks:
    - include: tasks/deploy-build-db.yml
    - include: tasks/dump-db.yml
    - include: tasks/normalstart-db.yml
    - include: tasks/deploy-build-fetcher.yml
    - include: tasks/dump-fetcher.yml
    - include: tasks/normalstart-fetcher.yml